export const USER_AUTHENTICATE = 'USER_AUTHENTICATE'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const CLEANING_ALERT_MESSAGE = 'CLEANING_ALERT_MESSAGE'